### ISSUE TITLE
can not acces metadata on storescp

### ISSUE THREAD

**Issue by larsdoise** [knopkem/dicom-dimse-native#13]

**Comment by larsdoise** [comment]
Hello,
I have a question with the startscp:
`dimse.startScp(JSON.stringify(
    {
        "source": {
            "aet": "DIMSE",
            "ip" : "127.0.0.1",
            "port": "9999"
        },
        "peers": [ // peers needed for C-MOVE destination
                {
                "aet": "CONQUESTSRV1",
                "ip" : "127.0.0.1",
                "port": "5678"
                }
            ],
        "storagePath": "./data",
        // "netTransferPrefer": "1.2.840.10008.1.2.4.80", // preferred network transfer syntax (accepted additional to default ts uncompressed)
        // "netTransferPropose": "1.2.840.10008.1.2.4.80", // proposed network transfer syntax (for outgoing associations)
        "writeTransfer": "", // write transfer syntax (storage only), keep empty to store original
        "permissive": true, // any AET can perform FIND,GET and STORE
        // "verbose": true // verbose logging
    }
    
    ), (result) => {
        if (result && result.length > 0) {
            try
            {
                console.log(result)    
                console.log(JSON.parse(result));
            }
            catch (e) {
                console.log(e, result);
            }
        }
});`
>hy does my code never log the result when i send a file? The file is saved on the server but i can never access the result. I am trying to insert some metadata from this file into another database than sqlite (that is standard included) for a project im working on. I know the library has a parse service but that one only works with files that are already on the system.

**Comment by knopkem** [comment]
The same issue was just recently closed: https://github.com/knopkem/dicom-dimse-native/issues/7
There are 2 reasons why this doesn't work right now:
* using the DCMTK code makes emitting from within the SCP hard, as this is deeply nested inside the dcmtk structure, it's only possible by modifying the original code (which I tried to avoid as much as possible to not introduce bugs and to make updates easier).
* the other reason is that somehow emitting from within the thread does not work reliably. I'm using this library: https://github.com/NickNaso/addon-event-emitter and emit is done in this example: https://github.com/nodejs/node-addon-examples/tree/main/emit_event_from_cpp/node-addon-api
The thing is that when emitting something very fast (e.g. within milliseconds) the javascript will 'drop messages' meaning it only gets some of them, which is not a good base to build on it. So for the moment I only use it for some debug messages.
However I noticed that there are other ways to pass stuff around, e.g. by calling threadSafeFunctions: https://github.com/nodejs/node-addon-api/blob/main/doc/threadsafe.md which might be worth looking into, I just didn't have the time (and priority as I don't need it for the apps that use this). 
I can't promise anything but will try to look into this in a spare minute. Otherwise, help is always appreciated.
