### ISSUE TITLE
Support printscp?

### ISSUE THREAD

**Issue by CloudWoR** [knopkem/dicom-dimse-native#22]
I need print dcm | png to dicom camera，Does this library support it？

**Comment by knopkem** [comment]
unfortunately not, sorry.

**Comment by CloudWoR** [comment]
will,Any recommendations？

**Comment by knopkem** [comment]
DICOM print is not easy, which is why there are not many free tools that do
that but you can find DICOM print (and if so, then they are quite basic) in
most professional medical software.
What you are probably looking for is a PRINT SCU (a tool that loads images
and sends them via DICOM to a PRINT SCP or DICOM Printer).
I know that DCMTK has such a tool, but usage is difficult (never tried):
https://support.dcmtk.org/docs/dcmprscu.html
Here is some talk about it: https://forum.dcmtk.org/viewtopic.php?t=538
It's probably simpler to use a complete workstation that allows printing,
you could try weasis: https://github.com/nroduit/Weasis#general-features
Hope this helps
