### ISSUE TITLE
scp receive this file throw error

### ISSUE THREAD

**Issue by suoc** [knopkem/dicom-dimse-native#3]
Try to send this file  to scp.[dicom file](http://66.42.110.234/download/1.dcm)

**Comment by knopkem** [comment]
ok, will have a look soon

**Comment by knopkem** [comment]
The file is invalid because the tag (0002,0010) (TransferSyntax) was added twice.
Sending with dcmtk gives:
`W: DcmItem: Invalid Element (0002,0010) found in data set
W: DIMSE Warning: (STORESCU,ANY-SCP): sendMessage: unable to convert dataset from 'JPEG Lossless, Non-hierarchical, Process 14' transfer syntax to 'Little Endian Implicit'
E: Store Failed, file: c:/test/invalid.dcm:
`
Check with dicom3tools: dcdump:
`Error - Tags out of order - trailing garbage, wrong transfer syntax, or not valid DICOM
`
