### ISSUE TITLE
Option to send base64 input stream through storeScu

### ISSUE THREAD

**Issue by 1443658** [knopkem/dicom-dimse-native#42]
Hi, really appreciate your effort on this project, it is great and easy to use.
I saw in storeScp there is an option to send via buffer as base64(**writeFile** = false), 
just wonder is there a way to send this base64 buffer through storeScu?
Thanks so much for the help!

**Comment by knopkem** [comment]
Hi, for storeScp setting storeOnly and writeFile does the following change: instead of automatically let the storeScp store the received DICOM files it passes the buffer (base64 encoded) of each file to the callback. This can be useful in certain scenarios e.g. where the files are directly processed.
For storeScu it would be the other way around, the files that should be transferred would be passed as base64 buffer array. Sending file by file is very inefficient via store scu (in general) so having the option to batch send is important I think.
I do think that this can be useful and should be easy to implement. Do you have a specific use-case for it?

**Comment by 1443658** [comment]
Well actually my app is acting like a proxy which receives dicom file from one side (storeScp), then send it out to another side(storeScu). 
So I am wondering if it is possible that when storeScp callback has that file buffer, I can directly send that base64 encoded buffer out using storeScu function without any physical files during the whole process.
Thanks again for your help!

**Comment by knopkem** [comment]
Ok, thanks for the explanation. I'll see if I find the time to implement this as this sounds easy and helpful.
However it sounds like this would not be very efficient as you would send each single file out to the receiver (image level store is usually slow due to the handshake overhead). I will try to allow an array of base64 encoded files so you could buffer a bit in memory. Will let you know. Cheers.

**Comment by knopkem** [comment]
@1443658 Is this feature still needed? Could implement it now.
