### ISSUE TITLE
capture dimse output

### ISSUE THREAD

**Issue by geezer78** [knopkem/dicom-dimse-native#63]
I would like to be able to capture the dimse output in my code.
currently its being sent to stdout which could be captured of course but makes it messy. 
I would prefer getting the output as an object with the results.

it would be great if that could be added.

**Comment by knopkem** [comment]
Indeed, this would be a nice improvement. The dimse output is currently produced by dcmtk via their internal logger, but this logger can be replaced. I will have a look at it.

**Comment by knopkem** [comment]
I tried adding a logforwarder that sends the captured logs to the js land. It did work to some extend but then crashed under heavy logging, so postponed this for now, but will try to find out a solution. Seems like the issue is rather with node-addon-api than dcmtk. Anyway, the latest version was changed to log dcmtk output to a rolling file called dicom.log in order to not slowdown the service.

**Comment by geezer78** [comment]
Wow, thanks for this and the update of dcmtk! I will check it out asap.

Kind regards,

Gijs

________________________________
